### ISSUE TITLE
Installation on macOS

### ISSUE THREAD

**Issue by jalanb** [magnetikonline/sysstat-graph#3]
I'm trying to use sysstatgraph on macOS using the following versions:

macOS Sierra, version 10.12.2
php, version 5.6.27
apache, version 2.4

I already have ~/Sites set up and have servers a number of (html/js) websites at http://localhost/~jalanb. This is the first time trying to serve a php site there.

I cloned this repo into `~/Sites/sysstatgraph`, editted the config file to change directory for the sar files (they are copied over to my machine from the webserver) and navigated the browser to http://localhost/~jalanb/sysstatgraph/index.php

What I see on the page:
```
execute(); ?>
Sysstat Graph

Generated by SysStat Graph Version 0.4
```
I have no experience with PHP, but it looks to me like the [execute() line](https://github.com/magnetikonline/sysstatgraph/blob/master/index.php#L9) is not actually executed, just shown.

The [instructions](http://magnetikonline.com/sysstatgraph/) say 

> On first run your SYSSTAT sarXX reports will be processed and a file defined by JSONSTRUCTUREFILENAME will be created for in-browser rendering

But the file `data.json` is not being created. 

What am I missing?

**Comment by magnetikonline** [comment]
Hey @jalanb - that's definitely a case where you can't execute PHP successfully via Apache.

Can you create a phpinfo.php file (or similar) in a document root path with the following contents?

```php
<?php
phpinfo();
```

See if you get a "Welcome to PHP message" / info page.

  Pete

**Comment by jalanb** [comment]
Thanks Pete, uncommented the php5 module in Apache conf, restarted, and now seeing sysstatgraph trying to create the `data.json` file.

However it doesn't seem to be finding any stats:
```shell
$ cd ~/Sites/sysstatgraph
$ cat data.json
{starttime: '1970-1-1',networkinterfacelist: [''],timepointlist: [],valuelist: {}}
```

Note - I'm not running on the original sa machine: I have copied `/var/log/sa` over from a production server to `/tmp/sa` on local dev machine, and am running on the dev machine.

I have updated config to point at `/tmp/sa`, are there other adjustments I should be making?

**Comment by magnetikonline** [comment]
@jalanb this, I fear may be your next problem! The format of `sar` files have changed quite a bit since I wrote this utiliy many years ago.

Can you confirm the version of SYSSTAT you have on your server(s)?

**Comment by jalanb** [comment]
We're on CentOS 6, and so our version of sysstat is `9.0.4-27.el6`

**Comment by magnetikonline** [comment]
Hey @jalanb - yeah I'm afraid I probably can't help you in the short term.

Last time I touched this project (over five years now!) - PHP 5.3.x was king... and it was (from my README web page!):
> Development is currently against version 9.1.1 - 9.0.6 & 9.0.3 also known to work.

So you might be out of luck - have you configured the network adaptor name in the config?

As in here: https://github.com/magnetikonline/sysstatgraph/blob/master/config.php#L4

**Comment by jalanb** [comment]
Thanks anyway @magnetikonline.

I was trying this because sysstat is already deployed on my servers. I think I'll switch over to installing collectl there instead.
