### ISSUE TITLE
PHP message: PHP Notice:  Undefined offset: 0 in buildjsonstructure.php on line 21

### ISSUE THREAD

**Issue by linuxitux** [magnetikonline/sysstat-graph#4]
I got this error on a fresh install using PHP 5.4.45 and sysstat 10.0.5-1. No data at all.

config.php:

    <?php
    define('SYSSTATDATAPATH','/var/log/sysstat');
    define('JSONSTRUCTUREFILENAME','data.json');
    define('NETWORKINTERFACELIST',serialize(array('lo','venet0')));

/var/log/sysstat/:

    total 57212
    -rw-r--r-- 1 root root 3754968 May 16 00:00 sa15
    -rw-r--r-- 1 root root 3760168 May 17 00:00 sa16
    -rw-r--r-- 1 root root 3760168 May 18 00:00 sa17
    -rw-r--r-- 1 root root 3760168 May 19 00:00 sa18
    -rw-r--r-- 1 root root 3754968 May 20 00:00 sa19
    -rw-r--r-- 1 root root 3754968 May 21 00:00 sa20
    -rw-r--r-- 1 root root 3760168 May 22 00:00 sa21
    -rw-r--r-- 1 root root 3754968 May 23 00:00 sa22
    -rw-r--r-- 1 root root 1643768 May 23 10:30 sa23
    -rw-r--r-- 1 root root 3350043 May 16 06:25 sar15
    -rw-r--r-- 1 root root 3354685 May 17 06:25 sar16
    -rw-r--r-- 1 root root 3350040 May 18 06:25 sar17
    -rw-r--r-- 1 root root 3354678 May 19 06:25 sar18
    -rw-r--r-- 1 root root 3350042 May 20 06:25 sar19
    -rw-r--r-- 1 root root 3350044 May 21 06:25 sar20
    -rw-r--r-- 1 root root 3350048 May 22 06:25 sar21
    -rw-r--r-- 1 root root 3350047 May 23 06:25 sar22

data.json:

    {starttime: '1969-12-31',networkinterfacelist: [''],timepointlist: [],valuelist: {}}root@linuxito:/var/www/linuxito.com/

**Comment by magnetikonline** [comment]
Hey @linuxitux,

    Just quickly - this will be due to the fact of version difference - this was built (many years ago!), and was designed for version of sysstat of `9.1.1 - 9.0.6 & 9.0.3` back from 2011.

I'm not supporting this anymore I'm afraid, just here for an archive.

Cheers
 
  Pete
